name: "MyBot"
description: "Scheduling Bot Hosting"
version: "1.0.0"
slug: "scheduling_bot"
init: false
ingress: true
ingress_port: 8099
panel_icon: "mdi:robot"
panel_title: "Discord Bot Status"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
